### ISSUE TITLE
d3 v4

### ISSUE THREAD

**Issue by miguelcobain** [mauriciopoppe/greuler#10]
It would be great to have this library to work with d4 v4.

If someone could lay out a plan for it I could try to tackle that.

**Comment by mauriciopoppe** [comment]
hey, sorry for the horrendous delay on my answer, I've started working on the update to d3 v4, stay tuned...

**Comment by mauriciopoppe** [comment]
- [ ] make the required modules of d3 a dependency
- [ ] migrate build system to rollup
- [ ] add webcola as a dependency? it would be awesome to treat the layout engine as a pluggable module

**Comment by mauriciopoppe** [comment]
I upgraded the app to use d3 v6, this is released in the alpha tag

```sh
npm install greuler@alpha
```
