### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by akud** [mauriciopoppe/greuler#11]
Just wanted to say thanks for writing greuler. I just used it to write a blog post about networks with an interactive visualization. greuler was great.

**Comment by mauriciopoppe** [comment]
Awesome! Happy to know you like it, can you send me the link of your blog post please?

**Comment by akud** [comment]
https://akud.github.io/visualization-blogs/posts/01_content_distribution_networks/index.html

I'm mostly exploring building interactive visualizations, so the idea in the post is kind of a toy problem.
