### ISSUE TITLE
how to make the graph draggable?

### ISSUE THREAD

**Issue by forestlightelf** [mauriciopoppe/greuler#13]
i try to make the graph like your example ,but it seems the graph is fixed
![image](https://user-images.githubusercontent.com/58362707/103733354-8c6e0f80-5024-11eb-996b-1d838a6b3411.png)

**Comment by mauriciopoppe** [comment]
This is a library that I don't maintain anymore, the dragging functionality should come out of the box, could you please use these two scripts instead?

```html
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.js"></script>
<script src="https://mauriciopoppe.github.io/greuler/scripts/lib/cola.v3.js"></script>
```

I think that the URL of the cola library is no longer compatible with this library, the one I have on the website is a snapshot of it

**Comment by forestlightelf** [comment]
i've already use the new url http://marvl.infotech.monash.edu/webcola/cola.js  but it seems not work.
part of my code is
https://paste.ubuntu.com/p/nF4ZCMjq65/
thank you for your kindness

**Comment by mauriciopoppe** [comment]
I've created a small working example here, sorry if the links on the main page are different:

https://codesandbox.io/s/cocky-sammet-e6sl6?file=/index.html

**Comment by mauriciopoppe** [comment]
`greuler` is now available as an npm module, check out the homepage:

```sh
npm install greuler@alpha
```
