### ISSUE TITLE
How to stop script 

### ISSUE THREAD

**Issue by izac1** [mauriciopoppe/greuler#9]
I try to write Topological sort and if i find a cycle i whant to stop script , i try a `return false` but its dont work .

**Comment by maurizzzio** [comment]
You may be using the non-documented `player.Generator` class, I'd gladly accept a PR to stop the animation when the value yielded is `false` although I'd rather make a custom player that suits my needs (the class is only intended for greuler demo purposes)

[These are the lines that need to be changed](https://github.com/maurizzzio/greuler/blob/master/src/player/Generator.js#L34-L39)
